name = "glusterfs"
description = "An example GlusterFS server with heketi and samba"

[[modules]]
name = "glusterfs"
version = "3.7.*"

[[modules]]
name = "glusterfs-cli"
version = "3.7.*"

[[modules]]
name = "heketi"
version = "2.0.*"

[[packages]]
name = "samba"
version = "4.2.*"
