name = "octave"
description = "Octave numerical computation system"

[[modules]]
name = "octave"
version = "3.8.*"

[[modules]]
name = "octave-general"
version = "1.3.*"

[[modules]]
name = "octave-image"
version = "2.2.*"

[[modules]]
name = "octave-signal"
version = "1.3.*"

[[packages]]
name = "atlas"
version = "3.10.*"
